<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ApiUser\Module'                        => __DIR__ . '/Module.php',
    'ApiUser\Entity\User' 					=> __DIR__ . '/src/ApiUser/Entity/User.php',
    'ApiUser\Entity\Role' 					=> __DIR__ . '/src/ApiUser/Entity/Role.php',
	'ApiUserTest\Framework\TestCase'        => __DIR__ . '/tests/ApiUser/Framework/TestCase.php',
    'ApiUserTest\SampleTest'                => __DIR__ . '/tests/ApiUser/SampleTest.php',
);
