<?php
// module/Application/view/application/index/import.phtml:
$title = 'Import Gravity Form Leads';
$this->headTitle($title);
?>
<h1>
<?php echo $this->escapeHtml($title); ?>
<span class="pull-right"> <a class="btn btn-info"
		href="<?php echo $this->url('home', array('action'=>'index'));?>">Back</a>
	</span>
</h1>
<hr>
<ul class="nav nav-pills nav-wizard">
	<li <?php echo ($this->stage == 1) ? ' class="active"' : ''; ?>><a
		href="javacript:void()">Import</a>
		<div class="nav-arrow"></div></li>
	<li <?php echo ($this->stage == 2) ? ' class="active"' : ''; ?>><div
			class="nav-wedge"></div> <a href="javacript:void()">Match</a>
		<div class="nav-arrow"></div></li>
	<li <?php echo ($this->stage == 3) ? ' class="active"' : ''; ?>><div
			class="nav-wedge"></div> <a href="javacript:void()">Confirm</a></li>
</ul>
<?php
$form = $this->form;
$form->setAttribute('action', 
		$this->url('home', array(
				'action' => 'import'
		)))
	->prepare();

echo $this->form()->openTag($form);
?>
<div class="row content-row">
<?php
if ($form->has('match') && 2 === $this->stage) :
	$match = $form->get('match');
	$fields = $this->fields;
	?>
<div class="col-md-12">
		<fieldset class="fieldset">
			<legend><?php echo $match->getLabel(); ?></legend>
	<?php
	if ($match instanceof Zend\Form\Fieldset) {
		foreach ($fields as $type => $class) {
			foreach ($class as $required => $section) {
				echo '<fieldset class="fieldset">';
				echo '<legend>' . $required . ' Fields</legend>';
				echo '<div class="row import-fields ' . $required . '">';
				foreach ($section as $description => $fieldName) {
					$element = $match->get($fieldName);
					switch ($type) {
						case 'text':
							echo "<div class='col-xs-12 col-md-6'>" . $this->formRow(
									$element) . "</div>\n";
							break;
						case 'select':
							if (in_array($description, $this->headings) &&
									 empty($element->getValue())) {
								$element->setValue($description)->setAttribute(
										"class", 
										$element->getAttribute("class") .
										 " match");
							}
							echo "<div class='col-xs-12 col-sm-6 col-md-4 col-lg-3'>" .
									 $this->formElement($element) . "</div>\n";
							break;
					}
				}
				echo '</div>';
				echo '</fieldset>';
			}
		}
	}
	?>
			<div class="row import-fields">
				<div class="col-md-12">
					<div class="well">
						<code>Leads Found: <?php echo $this->count; ?></code>
					</div>
				</div>
			</div>
		</fieldset>
		<hr>
		<div class="row">
			<div class="col-md-12"><?php echo $this->formRow($form->get('submit')); ?></div>
		</div>
	</div>
	<?php echo $this->formelement($form->get('leadTmpFile')); ?>



<?php elseif ($form->has('leadsUpload') && 1 === $this->stage) :
	$upload = $form->get('leadsUpload');
	?>
<div class="col-md-12">
		<fieldset class="fieldset">
			<legend><?php echo $upload->getLabel(); ?></legend>
			<div class="row import-fields">
				<div class="col-md-12">
					<?php echo $this->formRow($upload); ?>
					<hr>
				</div>
				<div class="col-md-12"><?php echo $this->formRow($form->get('submit')); ?></div>
			</div>
		</fieldset>
	</div>
<?php 
elseif ($this->data && 3 === $this->stage) :
	$confirm = $form->get('confirm');
	?>
<div class="col-md-12">
		<fieldset class="fieldset">
			<legend><?php echo $confirm->getLabel(); ?></legend>
			<div class="row import-fields">
				<div class="col-md-12">
					<?php echo $this->tableCollapse($this->data, $this->headings, $this->valid); ?>
				</div>
				<div class="col-md-12"><?php echo $this->formRow($form->get('submit')); ?></div>
			</div>
		</fieldset>
	</div>
<?php
	foreach ($form as $name => $element) {
		switch ($name) {
			case 'submit':
			case 'csrf':
				break;
			default:
				echo $this->formHidden($element);
				break;
		}
	}
	?>
<?php endif; ?>
	</div>
<?php echo $this->formHidden($form->get('csrf')); ?>
<?php echo $this->form()->closeTag(); ?>